
export interface PortfolioHolding {
  id: string; // Unique ID for this holding entry (generated by uuid)
  coinGeckoId: string; // CoinGecko ID (e.g., 'bitcoin')
  symbol: string; // Ticker symbol (e.g., 'BTC')
  name: string; // Coin name (e.g., 'Bitcoin')
  quantity: number;
  purchasePrice: number; // Average price per coin at the time of purchase in USD
}

export type NewPortfolioHolding = Omit<PortfolioHolding, 'id'>;

export interface EnrichedPortfolioHolding extends PortfolioHolding {
  currentPrice?: number | null;
  currentValue?: number | null;
  totalCost?: number | null;
  profitLoss?: number | null;
  profitLossPercentage?: number | null;
}
